These changes cause the following test failure:
PrimaryAuth events beacon loading shows an error if authClient returns with an error
   Expected 'Sign in failed!We found some errors. Please review the form and make corrections.' to be 'Sign in failed!'.
   Error: Expected 'Sign in failed!We found some errors. Please review the form and make corrections.' to be 'Sign in failed!'.
       at stack (file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:2338)
       at buildExpectationResult (file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:2308)
       at file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:858
       at file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:487
       at addExpectationResult (file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:802)
       at file:///home/vagrant/okta/okta-signin-widget/.grunt/grunt-contrib-jasmine/jasmine.js:2260
       at file:///home/vagrant/okta/okta-signin-widget/target/test/unit/main-tests.js:94605
       at _fulfilled (file:///home/vagrant/okta/okta-signin-widget/target/test/unit/main-tests.js:30248)
       at file:///home/vagrant/okta/okta-signin-widget/target/test/unit/main-tests.js:30277
       at file:///home/vagrant/okta/okta-signin-widget/target/test/unit/main-tests.js:30210